import { optionalString, optionalNumber, optionalBoolean, optionalId, pickDefined } from "../utils/validators.js";

export const SCHEDULE_LINE_ITEM_PROPERTIES = {
  product_id: { type: "number", description: "Product to bill. name, description, and product_category default from it." },
  name: { type: "string", description: "Line name on the invoice. A new line needs name or product_id." },
  description: { type: "string", description: "Longer text under the name" },
  quantity: { type: "number", description: "Quantity. Ignored for line types that count their own units (asset, contact, remote access, policy folder, vendor, Kabuto)." },
  retail_cents: { type: "number", description: "Price charged, in cents" },
  cost_cents: { type: "number", description: "Your cost, in cents" },
  price_retail: { type: "number", description: "Price charged, in dollars (alternative to retail_cents)" },
  price_cost: { type: "number", description: "Your cost, in dollars (alternative to cost_cents)" },
  taxable: { type: "boolean", description: "Taxable" },
  position: { type: "number", description: "Sort order on the invoice (default: bottom)" },
  product_category: { type: "string", description: "Product category (overwritten by the product's category when product_id is set)" },
  one_time_charge: { type: "boolean", description: "Bill once, then stop" },
  user_id: { type: "number", description: "Employee credited with the line (default: API token owner)" },
  recurring_type_id: {
    type: "number",
    enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    description: "Line type, which decides how quantity is counted: 1 recurring invoice, 2 data backup, 3 general subscription, 4 asset, 5 Kabuto, 6 contact, 7 Syncro Backup, 8 remote access, 9 policy folder, 10 third-party vendor, 11 Cloudberry",
  },
  asset_type_id: { type: "number", description: "Asset lines (type 4): bill the customer's assets of this type" },
  saved_asset_search_id: { type: "number", description: "Asset lines (type 4): bill assets matching this saved search instead of a type" },
  contact_field_type_id: { type: "number", description: "Contact lines (type 6): bill contacts by this custom field" },
  contact_field_answer_id: { type: "number", description: "Contact lines (type 6): only contacts with this answer to that field" },
  policy_folder_id: { type: "number", description: "Policy folder lines (type 9): bill the assets in this folder" },
  bill_nested_folders: { type: "boolean", description: "Policy folder lines (type 9): include sub-folders" },
  vendor_name: { type: "string", description: "Vendor lines (type 10): vendor to read usage from" },
  vendor_product_name: { type: "string", description: "Vendor lines (type 10): vendor product to bill" },
  bill_all_units: { type: "boolean", description: "Bill every unit, not just those over bill_units_threshold" },
  bill_units_threshold: { type: "number", description: "Units included before billing starts. Required when bill_all_units is false." },
  include_zero_charge: { type: "boolean", description: "Keep the line on the invoice even when it bills nothing" },
  m365_unit_type: { type: "string", enum: ["all", "consumed"], description: "Microsoft 365 vendor lines: bill licensed ('all') or consumed seats" },
  syncro_backup_billing_type: { type: "string", enum: ["license_count", "cloud_storage_usage"], description: "Syncro Backup lines (type 7): bill per license or per GB stored" },
  syncro_backup_credit_type: { type: "string", enum: ["global_credit", "per_asset_credit"], description: "Syncro Backup storage lines: included storage is global or per asset" },
  syncro_backup_bill_all: { type: "boolean", description: "Syncro Backup lines: bill all usage, ignoring the included allowance" },
  syncro_backup_bill_after_licenses: { type: "number", description: "Syncro Backup license lines: licenses included before billing starts" },
  syncro_backup_bill_after_storage: { type: "number", description: "Syncro Backup storage lines: GB included before billing starts" },
} as const;

export function buildScheduleLineItemBody(args: Record<string, unknown>): Record<string, unknown> {
  return pickDefined({
    product_id: optionalId(args.product_id),
    name: optionalString(args.name),
    description: optionalString(args.description),
    quantity: optionalNumber(args.quantity),
    retail_cents: optionalNumber(args.retail_cents),
    cost_cents: optionalNumber(args.cost_cents),
    price_retail: optionalNumber(args.price_retail),
    price_cost: optionalNumber(args.price_cost),
    taxable: optionalBoolean(args.taxable),
    position: optionalNumber(args.position),
    product_category: optionalString(args.product_category),
    one_time_charge: optionalBoolean(args.one_time_charge),
    user_id: optionalId(args.user_id),
    recurring_type_id: optionalNumber(args.recurring_type_id),
    asset_type_id: optionalId(args.asset_type_id),
    saved_asset_search_id: optionalId(args.saved_asset_search_id),
    contact_field_type_id: optionalId(args.contact_field_type_id),
    contact_field_answer_id: optionalId(args.contact_field_answer_id),
    policy_folder_id: optionalId(args.policy_folder_id),
    bill_nested_folders: optionalBoolean(args.bill_nested_folders),
    vendor_name: optionalString(args.vendor_name),
    vendor_product_name: optionalString(args.vendor_product_name),
    bill_all_units: optionalBoolean(args.bill_all_units),
    bill_units_threshold: optionalNumber(args.bill_units_threshold),
    include_zero_charge: optionalBoolean(args.include_zero_charge),
    m365_unit_type: optionalString(args.m365_unit_type),
    syncro_backup_billing_type: optionalString(args.syncro_backup_billing_type),
    syncro_backup_credit_type: optionalString(args.syncro_backup_credit_type),
    syncro_backup_bill_all: optionalBoolean(args.syncro_backup_bill_all),
    syncro_backup_bill_after_licenses: optionalNumber(args.syncro_backup_bill_after_licenses),
    syncro_backup_bill_after_storage: optionalNumber(args.syncro_backup_bill_after_storage),
  });
}
